### ISSUE TITLE
Support for UIKit+Mac (Catalyst) apps 

### ISSUE THREAD

**Issue by xjki** [IdeasOnCanvas/AppReceiptValidator#55]
It would be great to use AppReceiptValidator for iOS13/Catalina Catalyst apps. One option would be library compiled as new Xcode 11 .xcframework. 

From [Xcode 11 Beta Release Notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_3_release_notes)
`XCFrameworks make it possible to bundle a binary framework or library for multiple platforms —including iOS devices, iOS simulators, and UIKit for Mac — into a single distributable .xcframework bundle that your developers can use within their own applications. An .xcframework bundle can be added to an Xcode target’s Link Libraries phase and Xcode uses the right platform’s version of the included framework or library at build time. Creation of XCFrameworks is supported from the command line using xcodebuild -create-xcframework. Frameworks or libraries bundled in an XCFramework should be built with the Build Libraries for Distribution build setting set to YES.
`

Another option would be library as CocoaPod that compiles with the rest of code.

**Comment by hannesoid** [comment]
That would indeed be nice, I think Carthage is already ready for it (but this project not)! Also would be nice to provide a Swift Package Manager package but not sure how this works. Not sure if the OpenSSL stuff needs to be rebuilt too.
As currently this is not a priority for me/us, I'm sorryy I can't promise any news on this soon, feel free to experiment on a fork(?)

**Comment by funkenstrahlen** [comment]
Unfortunately Carthage does not look ready for Catalyst yet: https://github.com/Carthage/Carthage/issues/2799

It does not look like there is a lot of traction there.

Swift 5.3 added support for all kinds of assets in Swift Package Manager. This might offer the possibility to include an OpenSSL binary.

**Comment by hannesoid** [comment]
we just released a new version that uses swift package manager and should resolve this issue, although we don't maintain a catalyst app to test it with

**Comment by hannesoid** [comment]
pls create a new issue if you run in to problems
