### ISSUE TITLE
AppReceiptValidator always retrieves the same receipt, with the same inApp purchases even if the sandbox user is changed

### ISSUE THREAD

**Issue by KatkayApps** [IdeasOnCanvas/AppReceiptValidator#63]
This is something I have noticed while testing AppReceiptValidator: it always retrieves the same receipt with the same inapp purchases, even if I change the sandbox user. Why is that? Very strange.

What I mean is this: I run the app, it asks me for the App Store credentials, I login with a sandbox user, let's say a@example.com.

I purchase a few items. 

I run the app again with another app store credentials, b@example.com

I retrieve the receipt and it shows the inapp purchases that were purchased by a@example.com.

Aren't the purchases bound to a specific user?

I am testing this under macOS. I have tried to purchase something with the second sandbox user to see if the receipt would refresh. NOPE. 

Also tried several exit(173) + macOS restarts. NOPE.

**Receipt always comes with the purchases done by the first user who purchased inapps with the application.**

I suspect this is an error from Apple, what is expected, given their lack of love for developers.

**Comment by aquarius** [comment]
https://twitter.com/hannesoid/status/1229731041092308997?s=21
