### ISSUE TITLE
Build for Mac Arm (Apple Silicon) - anyone managed?

### ISSUE THREAD

**Issue by yellow8-vom** [IdeasOnCanvas/AppReceiptValidator#74]
Anyone managed to compile an app for macOS Big Sur (Xcode 12.2) with AppReceiptValidator?

carthage update fails with the following logs:

`
Build settings from configuration file '/tmp/static.xcconfig.NVALzV':
    EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))
    EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = arm64 arm64e armv7 armv7s armv6 armv8
    EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12B5044c = arm64 arm64e armv7 armv7s armv6 armv8

note: Using new build system
note: Building targets in parallel
note: Using codesigning identity override: 
note: Planning build
note: Constructing build description
error: The linked library 'libcrypto.a' is missing one or more architectures required by this target: arm64. (in target 'AppReceiptValidator macOS' from project 'AppReceiptValidator')
error: The linked library 'libssl.a' is missing one or more architectures required by this target: arm64. (in target 'AppReceiptValidator macOS' from project 'AppReceiptValidator')
`

**Comment by hannesoid** [comment]
please also try the recommended PR/branches in #70

**Comment by yellow8-vom** [comment]
Yep, this branches works. Thank you!

**Comment by hannesoid** [comment]
we just released a new version that uses swift package manager and should resolve this issue
